name: Bump packages on schedule or request

on:
  workflow_dispatch:
    inputs:
      casks:
        description: Space-separated cask tokens to bump
        required: false
        type: string
      formulae:
        description: Space-separated formula tokens to bump
        required: false
        type: string
  schedule:
    - cron: '20 */23 * * *'

permissions:
  contents: read

jobs:
  autobump:
    if: github.repository == 'Zach677/homebrew-star'
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: false
          cask: true

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@main
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'ZachTestBot' }}

      - name: Get list of autobump packages
        id: autobump
        run: |
          tap_repo="$(brew --repo Zach677/star)"
          echo "cask_list=$(xargs < "${tap_repo}/.github/autobump.txt")" >> "$GITHUB_OUTPUT"
          echo "formula_list=$(xargs < "${tap_repo}/.github/autobump-formulae.txt")" >> "$GITHUB_OUTPUT"

      - name: Bump packages
        uses: Homebrew/actions/bump-packages@main
        continue-on-error: true
        with:
          token: ${{ secrets.HOMEBREW_STAR_REPO_WORKFLOW_TOKEN }}
          casks: ${{ inputs.casks || steps.autobump.outputs.cask_list }}
          formulae: ${{ inputs.formulae || steps.autobump.outputs.formula_list }}
        env:
          Zach_TEST_BOT_AUTOBUMP: 1
